server:
    port: 9099
    
spring:
  profiles:
    active: "@activatedProperties@"  jpa:    hibernate:      ddl-auto: update
    show-sql: false    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
        
#actuator health report
management:  endpoint:    health:      show-details: always  endpoints:    web:      exposure:        include:        - health
        - metrics
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true        

# app info           
info:
  team:
    name: MeasureMe
  version: 1.0
  project:
    description: Monitoring website response time
---

spring:
  profiles:
  - development
  thymeleaf:
    cache: false
  datasource:
    username: user
    password: password
    url: ""  jpa:
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true

server:
  port: 80
  
# logback file output  
logging:
  level:
    root: info
    org.hibernate: info
    org.springframework: info

---

spring:
  profiles:
  - production
# needs to populate at runtime  datasource:    username: ""    password: ""    url: ""
    
# logback file output
logging:
  level:
    root: warn
    org.hibernate: error
    org.springframework: error
    

server:
  port: 9099
  compression:
    enabled: true
    mime-types:
    - text/html, text/css, application/json
    min-response-size: 4096
 